### ISSUE TITLE
Using the 'mangle' option in uglifyjs throws an error

### ISSUE THREAD

**Issue by davidbarratt** [wikimedia/mediawiki-title#27]
When using [uglifyjs](https://www.npmjs.com/package/uglifyjs) with the `--mangle` option, this library throws an error like this:
```
TypeError: Cannot read property '*' of undefined
    at o.getNormalizedText (http://127.0.0.1:8888/bundles/bundle.js:30:305279)
    at t.value (http://127.0.0.1:8888/bundles/bundle.js:35:343545)
    at http://127.0.0.1:8888/bundles/bundle.js:35:342954
    at Array.map (native)
    at t.project (http://127.0.0.1:8888/bundles/bundle.js:35:342929)
    at t._next (http://127.0.0.1:8888/bundles/bundle.js:16:60025)
    at t.next (http://127.0.0.1:8888/bundles/bundle.js:1:53735)
    at t.next (http://127.0.0.1:8888/bundles/bundle.js:30:117041)
    at XMLHttpRequest.r (http://127.0.0.1:8888/bundles/bundle.js:30:118620)
```

Here is the code that is calling the library that is throwing the error:
https://github.com/wikimedia/takedown-tools/blob/bc98a5e241248429ca5ae316dcb0b43b63338efb/client/components/fields/select-pages.js#L66-L77

It looks like the namespace gets an `_id` of `NaN` which then throws an error when `title.getNamespace().getNormalizedText()` is called.

The workaround is to not use `--mangle` but that produces builds that are much larger.

**Comment by cscott** [comment]
This seems like a bug in `uglifyjs`?
